In [1]:
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats as s


In [2]:
from properInput2 import generate_dot 
import pyNN.nest as sim

CSAConnector: libneurosim support not available in NEST.
Falling back on PyNN's default CSAConnector.
Please re-compile NEST using --with-libneurosim=PATH


/home/alberto/.local/lib/python3.6/site-packages/pyNN/nest/__init__.py:53: UserWarning:Unable to install NEST extensions. Certain models may not be available.


In [3]:
inputBar = generate_dot(30,30,1000)
inputBar = inputBar.transpose(2,1,0)

In [4]:
#Thresholding
random = np.random.rand(1000,30,30)
spk = inputBar > random # 
i=151
plt.matshow(spk[i])
plt.matshow(inputBar[i])

spk[i].shape

(30, 30)

In [5]:
cellSources = []
for i in range(1000):
    cellSources.append(np.unique(np.where(spk[i].reshape(900,1)==True)))
    
print(len(cellSources))
cellSources?
cellSources

1000


[array([  0, 121, 145, 186, 400, 431, 435, 461, 464, 465, 520, 595, 615,
        655, 686, 723, 780, 800]),
 array([  0,   7,  15,  16,  49,  62, 153, 173, 232, 284, 366, 386, 393,
        405, 429, 434, 435, 463, 464, 465, 496, 583, 594, 630, 675, 704,
        780, 781, 793, 800, 889, 891]),
 array([  0,  49,  57,  92, 118, 135, 203, 245, 360, 374, 405, 434, 435,
        465, 479, 484, 563, 615, 694, 697, 709, 733, 782, 796, 803, 865,
        871, 880]),
 array([  0,  92, 164, 434, 435, 440, 465, 471, 487, 496, 553, 643, 852,
        861, 871, 898]),
 array([  0,  13, 114, 181, 209, 220, 262, 285, 342, 382, 392, 434, 435,
        464, 466, 478, 526, 571, 608, 611, 613, 642, 675, 678, 698, 762,
        785, 825, 888]),
 array([  0,  14,  17,  53,  64, 165, 206, 300, 317, 330, 434, 435, 464,
        465, 474, 488, 495, 624, 646, 672, 684, 720, 731, 737, 797, 821,
        825]),
 array([  0, 105, 126, 134, 283, 318, 324, 399, 421, 428, 434, 435, 463,
        465, 538, 549, 705, 750, 763,

In [172]:
times = []
neurons = []
pair = []
for instants in range(1000):
    for instantCells in range(len(cellSources[instants])):
        #print(cellSources[i])
        for cells in range(900):
            if cellSources[instants][instantCells] == cells :
                neurons = neurons + [cells]
                times = times + [instants]
spikeTimes = []
spikeTimes = [[1] for _ in range(900)]

for i in range(len(neurons)):
    for j in range(900):
        if neurons[i] == j:
            spikeTimes[j] = spikeTimes[j] + [times[i]+2]



In [173]:
spikeTimes

[[1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  

In [126]:
for i in range(len(neurons)):
    for j in range(900):
        if neurons[i] == j:
            spikeTimes[j]= spikeTimes[j] + [times[i]]

In [133]:
x

NameError: name 'x' is not defined

In [52]:
neurons[0:10]
#times[0:10]

[0, 121, 145, 186, 400, 431, 435, 461, 464, 465]

In [ ]:
#building a simple net with 129 neurons as the stimulus has 129 steps
#and giving to it the dot input as sequential spike sources
sim.setup(timestep=1,
        min_delay=1,
        max_delay=1,
        debug=0)

nCells = 900#inputSources[0] #129
cell_pars = {
        'v_thresh': -48.0,
        'v_reset': -70.0,
        'tau_refrac': 2.0,
        'tau_syn_E': 5.0,
        'tau_syn_I': 5.0,
        'v_rest': -65.0,
        'i_offset': 0.0}

popE = sim.Population(nCells,
        sim.IF_cond_exp,
        cell_pars,
        label="2D-bumpNN")

popE.record(['spikes','v','gsyn_exc','gsyn_inh'])
print("pop", popE)


In [ ]:
t = 1000
pop=900
cellSources = []
for i in range(t):
    cellSources.append(np.unique(np.where(spk[i].reshape(pop,1)==True)))

inputWeight = 0.25
inputDelay = 1
for i in range(900):
    #print(len(cellSources[i]))
    connectors = connectors + [(i, i,inputWeight,inputDelay)]

spikeSource = sim.Population(900,
                                 sim.SpikeSourceArray,{'spike_times': ([100,200,300])},
                                 label="startSpikes")
    
spikeSource.record(['spikes'])
projections = sim.FromListConnector(connectors)      
projSource = sim.Projection(spikeSource,popE,
            connector = projections,
            receptor_type = "excitatory",
            label = "source_connections")

print(list(connectors))


In [ ]:
###---GETTING DATA
for i in range(3):
    if spikes_outE.segments[0].analogsignals[i].name == 'v':
        E_v = spikes_outE.segments[0].analogsignals[i]
    if spikes_outE.segments[0].analogsignals[i].name == 'gsyn_exc':
        E_gsynE = spikes_outE.segments[0].analogsignals[i]
    if spikes_outE.segments[0].analogsignals[i].name == 'gsyn_inh':
        E_gsynI = spikes_outE.segments[0].analogsignals[i]
    #print(A_dataE.analogsignals[i].name)

for i in range(3):
    if spikes_outI.segments[0].analogsignals[i].name == 'v':
        I_v = spikes_outI.segments[0].analogsignals[i]
    if spikes_outI.segments[0].analogsignals[i].name == 'gsyn_exc':
        I_gsynE = spikes_outI.segments[0].analogsignals[i]
    if spikes_outI.segments[0].analogsignals[i].name == 'gsyn_inh':
       I_gsynI = spikes_outI.segments[0].analogsignals[i]
    #print(A_dataI.analogsignals[i].name)

# Spike sources
inputs = spikeSources.segments[0].spiketrains

# Transpose data
E_v=np.transpose(E_v)
E_gsynE = np.transpose(E_gsynE)
E_gsynI = np.transpose(E_gsynI)
I_v=np.transpose(I_v)
I_gsynE = np.transpose(I_gsynE)
I_gsynI = np.transpose(I_gsynI)

In [ ]:
# GET DATA
# Excitatory cells
dataE = popE.get_data().segments[0]
E_spikes = dataE.spiketrains

for i in range(3):
    if dataE.analogsignals[i].name == 'v':
        E_v = dataE.analogsignals[i]
    if dataE.analogsignals[i].name == 'gsyn_exc':
        E_gsynE = dataE.analogsignals[i]
    if dataE.analogsignals[i].name == 'gsyn_inh':
        E_gsynI = dataE.analogsignals[i]
    print(dataE.analogsignals[i].name)
    
    
# Source
inSpikes = spikeSource.get_data().segments[0].spiketrains
inSpikes[0]

In [ ]:
plt.eventplot(E_spikes, colors='red')


In [ ]:
fig = plt.figure(figsize=(6,12))
fig.suptitle("Spike trains in Sources and E layers", fontsize=18)

ax = fig.add_subplot(4,1,1)
im = plt.eventplot(inSpikes, colors='blue')
ax.set_title("Spikes in Sources Layer ", y=1.10, fontsize=16)
ax.set_xlabel("[ms]", fontsize=14); 
ax.set_ylabel("neurons", fontsize=14)
#spikeSourceTimes[-1]

ax = fig.add_subplot(4,1,2)
im = plt.eventplot(E_spikes, colors='red')
ax.set_title("Spikes in E Layer ", y=1.10, fontsize=16)
ax.set_xlabel("[ms]", fontsize=14); 
ax.set_ylim(350,550)

ax.set_ylabel("neurons", fontsize=14)
fig.suptitle("Spike trains in Sources and E layers", fontsize=18)

ax = fig.add_subplot(4,1,3)
im=ax.matshow(E_v.T); fig.colorbar(im)
ax.set_title("[mV] in E layer", fontsize=14,y=1.15)
ax.set_xlabel("[ms]", fontsize=14); 
ax.set_ylabel("neurons", fontsize=14)
#ax.set_ylim(0,len(spikeSourceTimes))  

ax = fig.add_subplot(4,1,4)
im=ax.matshow(E_gsynE.T); fig.colorbar(im)
ax.set_title(" Exc [uS] in E layer", fontsize=14,y=1.15)
ax.set_xlabel("[ms]", fontsize=14); 
ax.set_ylabel("neurons", fontsize=14)
#ax.set_ylim(0,len(spikeSourceTimes))  

fig.subplots_adjust(hspace=0.75,wspace=0)

In [ ]:
E_varV = []
for i in range(len(E_v)):
    E_varV.append([np.var(E_v[i])])
a=np.asarray(E_varV)
a=a
a.resize(30,30)
plt.matshow(a)
a.shape

In [ ]:
E_var_gsynE = []
for i in range(len(E_gsynE.T)):
    c = E_gsynE.T
    E_var_gsynE.append([np.var(c[i])])
b=np.asarray(E_var_gsynE)
b.resize(30,30)
plt.matshow(b)
b.shape
len(E_gsynE)